apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.5-fpm
          env:
            - name: WORDPRESS_DB_HOST
              value: "mariadb"    # Service name of MariaDB
            - name: WORDPRESS_DB_USER
              value: "wpuser"
            - name: WORDPRESS_DB_PASSWORD
              value: "wppassword"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
            - name: fpm-config
              mountPath: /usr/local/etc/php-fpm.d/zz-status.conf
              subPath: zz-status.conf
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: fpm-config
          configMap:
            name: wp-fpm-status
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - name: php-fpm
      protocol: TCP
      port: 9000
      targetPort: 9000
