# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Base VM OS configuration.
  config.vm.box = "ubuntu/focal64"
  config.vm.box_check_update = false
  config.vm.provider :virtualbox do |v|
    v.memory = 5120
    v. cpus = 4
  end


  # Define VMs with static private IP addresses.
  boxes = [
    {
      :name => "node1",
      :ip => "192.168.99.211",
    },
    {
      :name => "node2",
      :ip => "192.168.99.212",
    },
    {
      :name => "node3",
      :ip => "192.168.99.213",
    }
  ]

  # Provision each of the VMs.
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
      config.vm.provision "shell", inline: <<-SHELL
        echo "ssh-rsa YOUR_PUBLIC_KEY" >> /home/vagrant/.ssh/authorized_keys
        sudo apt-get update
        sudo apt install -y python3 python3-pip
        sudo swapoff -a
        sudo sed -i '/ swap / s/^/#/' /etc/fstab
      SHELL
      end
    end
  end